# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brent Schneider
email: info [at] milkshakeinteractive.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://brentschneider.github.io/" # the base hostname & protocol for your site
twitter_username: webmedic
github_username:  brentschneider

# Build settings
markdown: kramdown
permalink: /:title

# Default settings for posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Brent Schneider
      layout: "post"
      comments: false
